### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by rvdleun** [rvdleun/onoffice#1]
**Goal**

To get On/Office running on a Linux distro.

**Description**

The application is built with Electron, so should technically be portable to Linux. I haven't had fully time to explore how to handle this, and the one time I tried to run On/Office in a virtual Ubuntu environment led to a number of errors.

I also don't have enough experience with building applications for Linux, in particular with different distros. Most of my experience comes from Ubuntu, and I don't know how big the differences are to release the application on several distros. 

Will likely need some help here or research more into it.

**Deliverables**

* To get On/Office working on a single distro. Personal preference is Ubuntu, but any will do for a start.
* Clear instructions on how to build and deploy a Linux package.

**Comment by Kilian** [comment]
The app runs on ubuntu and i managed to get it streaming to my oculus go!

* There seems to be some issue with storing the pin number
* It spends a lot of time on "requesting virtual cursor"
* there are a number of 400 websocket errors, though I don't know if this is an issue

**Comment by rvdleun** [comment]
That's really good news. Did you have to install anything specifically, or did it just work out of the box?

* There seems to be some issue with storing the pin number
Hmm, I wonder if it has issues storing any data overall. If you change the background image and reload the app, does it persist the image?

* It spends a lot of time on "requesting virtual cursor"
This reminds me of a different bug(which I should add to the issues list) and I wonder if it's related.

The bug is as follows: If you have multiple monitors, then it will keep waiting until you've moved the cursor over the streaming monitor. Did this happen by any chance?

* there are a number of 400 websocket errors, though I don't know if this is an issue
Hmm, I'm not sure if I've seen this before. So far, it's not causing any errors?

**Comment by Kilian** [comment]
#1. The image does not persist either.
#2. That's probably it! I'll try it later.
#3. Not that I can tell.

**Comment by rvdleun** [comment]
So... _ahem_, it seems that there was a bug where the image wasn't actually retrieved from storage, so that feature wasn't working on any of the platforms. Just committed a fix(https://github.com/rvdleun/onoffice/commit/2c4377432417bfe289748bb1991743afb9f02745) and new builds were created. I'm going to see if it is fixed for Windows and Mac, and will likely do a  1.0.1 release during the weekend.  (after removing the console messages)

If you have the time, could you download the new Linux build and see if the background image now persists?

**Comment by rvdleun** [comment]
Just did some testing in VirtualBox, and everything seems to be in working order. The background image and pincode persisted over time as well. I just may release an Ubuntu version this weekend.

**Comment by rvdleun** [comment]
Just release version 1.1.0, along with a Linux version. Seems to work in my VirtualBox environment. 🤞
