### ISSUE TITLE
Support for multiple screens

### ISSUE THREAD

**Issue by rvdleun** [rvdleun/onoffice#4]
**Goal**

To let the user add more screens into the virtual environment

**Description**

I briefly played with getting multiple screens to show up in the virtual environment, and was able to get it to work. However, there were still some mishaps here and there, and I preferred to focus on getting a first release out before focusing on this 

**Deliverables**

* Letting the user pick multiple screens in the Desktop Application
* Display multiple screens in the virtual environment

**Comment by Kilian** [comment]
The major issue seems to be that you get the mouse position in reference to the primary screen, but then map it onto the entire (multi-screen) viewport. If you have two monitors with identical resolutions, the virtual mouse moves twice the distance compared to the real mouse position.

**Comment by rvdleun** [comment]
This feature is now available in the `develop` branch and will be in the next major release.

**Comment by rvdleun** [comment]
Added in version 1.2.0
